FROM centos:latest
MAINTAINER Simon Mucha version: 0.1

######################################################################
# rabbitmq installation 
##########################
# src: https://github.com/CentOS/CentOS-Dockerfiles/blob/master/rabbitmq/centos7/Dockerfile

RUN yum -y update; yum clean all
RUN yum -y install epel-release; yum clean all
RUN yum -y install pwgen wget logrotate rabbitmq-server; yum clean all
RUN /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management

#
# add run/set passwd script
ADD run-rabbitmq-server.sh /run-rabbitmq-server.sh
RUN chmod 750 ./run-rabbitmq-server.sh

# 
# expose some ports
#
# 5672 rabbitmq-server - amqp port
# 15672 rabbitmq-server - for management plugin
# 4369 epmd - for clustering
# 25672 rabbitmq-server - for clustering
EXPOSE 5672 15672 4369 25672

#
# entrypoint/cmd for container
# we will set a random password and add one vhost for development
ENV DEVEL_VHOST_NAME develop

CMD ["sh /run-rabbitmq-server.sh"]

######################################################################
# FMN.SSE
#############

# Setup the OS env
RUN yum -y install git python python-devel python-virtualenvwrapper rabbitmq-server python-pip gcc libffi-devel openssl-devel zeromq-devel

# Create the pyenv
RUN virtualenv venv
RUN source venv/bin/activate

# Clone the repo
RUN git clone https://github.com/fedora-infra/fmn.sse.git

WORKDIR "./fmn.sse"

# Install py dependencies
RUN pip install --upgrade setuptools
RUN python setup.py install

RUN exec /usr/sbin/rabbitmq-server &
# Add some data to rabbitmq
RUN pip install pytz
RUN python dev-data.py


# Expose
# 8080 fmn.sse url
EXPOSE 8080
